In [1]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day","hour_range"
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ",
        "10m_rate",
        "20m_rate",
        "30m_rate",
        "40m_rate",
        "50m_rate",
        "60m_rate",
        "70m_rate",
        "80m_rate",
        "90m_rate",
        "100m_rate",
        "110m_rate",
        "120m_rate",
        "130m_rate",
        "140m_rate",
        "150m_rate",
        "160m_rate",
        "170m_rate",
        "180m_rate",
        "190m_rate",
        "200m_rate",
        "210m_rate",
        "220m_rate",
        "230m_rate",
        "240m_rate",
        "250m_rate",
        "260m_rate",
        "270m_rate",
        "280m_rate",
        "290m_rate",
        "300m_rate"
        ])


    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    df_feature["hour_range"] = df["hour_range"]
    
    i = 10
    while i != 300 + 10:
        df_feature[str(i)+"m_rate"] = df["Close"].pct_change(int(i/10))
        i += 10
#     df_feature["10m_rate"] = df["Close"].pct_change()
#     df_feature["30m_rate"] = df["Close"].pct_change(3)
#     df_feature["60m_rate"] = df["Close"].pct_change(6)
#     df_feature["120m_rate"] = df["Close"].pct_change(12)

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
    c=[0,0,0]
    
    
    def classify(x):
        percent = 0.05

        if x<-percent:
            c[0]+=1
            return 0
        elif -percent<x<percent:
            c[1]+=1
            return 1
        elif percent<x:
            c[2]+=1
            return 2
       

    classified = pd.DataFrame(columns=["class"])
    classified["class"] = df_feature["120m_rate"].apply(lambda x: classify(x))

    classified = classified.shift(-1)
    
    
    
    df_adjusted=df_feature[30:len(df_feature)-2]
    classified=classified[30:len(classified)-2]
    
    print(c)
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)

#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
#print(clf.feature_importances_)

KeyboardInterrupt: 

In [1]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day",
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ",
        "10m_rate",
        "30m_rate",
        "60m_rate",
        "120m_rate"
        ])


    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    df_feature["10m_rate"] = df["Close"].pct_change()*100
    df_feature["30m_rate"] = df["Close"].pct_change(3)*100
    df_feature["60m_rate"] = df["Close"].pct_change(6)*100
    df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
    c=[0,0,0]
    
    
    def classify(x):
        percent = 0.05

        if x<-percent:
            c[0]+=1
            return 0
        elif -percent<x<percent:
            c[1]+=1
            return 1
        elif percent<x:
            c[2]+=1
            return 2
       

    classified = pd.DataFrame(columns=["class"])
    classified["class"] = df_feature["120m_rate"].apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-12)
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-12]
    classified=classified[30:len(classified)-12]
    
    print(c)
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)

#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
#print(clf.feature_importances_)

[111734, 147110, 117415]
0.43957153868644183
[[ 6250 10666  5363]
 [ 4798 19504  5162]
 [ 4912 11269  7322]]
[0.39160401 0.47066773 0.41026503]


In [3]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day",
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ",
        "10m_rate",
        "30m_rate",
        "60m_rate",
        "120m_rate"
        ])


    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    df_feature["10m_rate"] = df["Close"].pct_change()*100
    df_feature["30m_rate"] = df["Close"].pct_change(3)*100
    df_feature["60m_rate"] = df["Close"].pct_change(6)*100
    df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
    c=[0,0,0]
    
    
    def classify(x):
        percent = 0.05

        if x<-percent:
            c[0]+=1
            return 0
        elif -percent<x<percent:
            c[1]+=1
            return 1
        elif percent<x:
            c[2]+=1
            return 2
       

    classified = pd.DataFrame(columns=["class"])
    classified["class"] = df_feature["120m_rate"].apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-12)
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-12]
    classified=classified[30:len(classified)-12]
    
    print(c)
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.7)


#y_ravel=np.ravel(y_train)

#print(X_train, y_train)

search_params = {
     'n_estimators'      : [5, 10, 20, 30, 50, 100, 300],
      'max_features'      : [3, 5, 10, 15, 20],
      'random_state'      : [2525],
      'n_jobs'            : [1],
      'min_samples_split' : [3, 5, 10, 15, 20, 25, 30, 40, 50, 100],
      'max_depth'         : [3, 5, 10, 15, 20, 25, 30, 40, 50, 100]
}

from sklearn.model_selection import cross_val_score
from bayes_opt import BayesianOptimization


def randomforest_cv(n_estimators, min_samples_split, max_features):
    val = cross_val_score(
        RandomForestClassifier(
            n_estimators=int(n_estimators),
            min_samples_split=int(min_samples_split),
            max_features=max_features,
            random_state=0
        ),
        X_train, y_train,
        scoring = 'accuracy',
        cv = 3, # 3-fold
        n_jobs = -1 # use all CPUs
    ).mean()
    return val

randomforest_cv_bo = BayesianOptimization(
    randomforest_cv,
    {'n_estimators': (10, 500),
    'min_samples_split': (2, 300),
    'max_features': (0.1, 0.999)}
)

gp_params = {"alpha": 1e-5}
randomforest_cv_bo.maximize(n_iter=50, **gp_params)
print(randomforest_cv_bo.res['max']['max_val'])
print(randomforest_cv_bo.res['max']['max_params'])



# clf = RandomForestClassifier()
# clf.fit(X_train, y_train)
# print(accuracy_score(y_test, clf.predict(X_test)))

# #X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
# #print(accuracy_score(y_real, clf.predict(X_real)))

# from sklearn.metrics import confusion_matrix
# print(confusion_matrix(y_test, clf.predict(X_test)))

# from sklearn.metrics import precision_score
# print(precision_score(y_test, clf.predict(X_test), average=None))

# import pickle
# filename = 'RF_01.sav'
# pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
#print(clf.feature_importances_)

[111734, 147110, 117415]
|   iter    |  target   | max_fe... | min_sa... | n_esti... |
-------------------------------------------------------------
|  1        |  0.4325   |  0.7677   |  206.1    |  399.2    |
|  2        |  0.433    |  0.2855   |  161.3    |  379.8    |
|  3        |  0.4331   |  0.2617   |  31.99    |  127.6    |
|  4        |  0.436    |  0.1338   |  76.52    |  256.1    |
|  5        |  0.4325   |  0.2854   |  110.9    |  92.33    |
|  6        |  0.4327   |  0.5311   |  18.44    |  288.4    |
|  7        |  0.4323   |  0.5797   |  75.79    |  256.4    |
|  8        |  0.4305   |  0.7171   |  168.0    |  54.45    |
|  9        |  0.4356   |  0.1357   |  89.49    |  200.1    |
|  10       |  0.4267   |  0.1632   |  196.5    |  14.2     |
|  11       |  0.4324   |  0.5956   |  231.4    |  304.3    |
|  12       |  0.4336   |  0.3083   |  18.44    |  268.0    |
|  13       |  0.4337   |  0.5948   |  45.92    |  425.7    |
|  14       |  0.4334   |  0.442    |  93.91 

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [5]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day",
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ",
        "10m_rate",
        "30m_rate",
        "60m_rate",
        "120m_rate"
        ])


    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    df_feature["10m_rate"] = df["Close"].pct_change()*100
    df_feature["30m_rate"] = df["Close"].pct_change(3)*100
    df_feature["60m_rate"] = df["Close"].pct_change(6)*100
    df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
    c=[0,0,0,0]
    
    
    def classify(x):
        percent = 0.04

        if x<-percent:
            c[0]+=1
            return 0
        elif -percent<x<=0:
            c[1]+=1
            return 1
        elif 0<x<percent:
            c[2]+=1
            return 2
        elif percent<x:
            c[3]+=1
            return 3
       

    legs = 30
    
    classified = pd.DataFrame(columns=["class"])
    classified["class"] = df_feature[str(legs) + "m_rate"].apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-1)
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-int(legs/10)]
    classified=classified[30:len(classified)-int(legs/10)]
    
    print(c)
    
    print(classified.isnull().sum())
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)
#print(y_train.isnull().any())
#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
#print(clf.feature_importances_)

[81527, 106937, 103355, 84449]
class    0
dtype: int64
0.5249308951732936
[[ 9873  4209  1250  1015]
 [ 3881 10375  5100  1851]
 [ 1781  6029  9164  3913]
 [ 1083  1666  3970 10088]]
[0.59411482 0.46568517 0.47033463 0.59809095]


In [5]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "Close",
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day",
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ",
        "10m_rate",
        "20m_rate",
        "30m_rate",
        "40m_rate",
        "50m_rate",
        "60m_rate",
        "70m_rate",
        "80m_rate",
        "90m_rate",
        "100m_rate",
        "110m_rate",
        "120m_rate",
        "130m_rate",
        "140m_rate",
        "150m_rate",
        "160m_rate",
        "170m_rate",
        "180m_rate",
        "190m_rate",
        "200m_rate",
        "210m_rate",
        "220m_rate",
        "230m_rate",
        "240m_rate",
        "250m_rate",
        "260m_rate",
        "270m_rate",
        "280m_rate",
        "290m_rate",
        "300m_rate"
        ])


    df_feature["Close"] = df["Close"]
    
    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    
    i = 10
    while i != 300 + 10:
        df_feature[str(i)+"m_rate"] = df["Close"].pct_change(int(i/10))*100
        i += 10
#     df_feature["10m_rate"] = df["Close"].pct_change()*100
#     df_feature["30m_rate"] = df["Close"].pct_change(3)*100
#     df_feature["60m_rate"] = df["Close"].pct_change(6)*100
#     df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
#     c=[0,0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=0:
#             c[1]+=1
#             return 1
#         elif 0<x<percent:
#             c[2]+=1
#             return 2
#         elif percent<x:
#             c[3]+=1
#             return 3
       
    
#     c=[0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=percent:
#             c[1]+=1
#             return 1
#         elif percent<x:
#             c[2]+=1
#             return 2
       
    
    
    c=[0,0]
    
    
    def classify(x):
        #percent = 0.06

        if x<0:
            c[0]+=1
            return 0
        elif 0<=x:
            c[1]+=1
            return 1

        
        
    legs = 60
    
    classified = pd.DataFrame(columns=["class"])
    classified["class"] = df_feature[str(legs) + "m_rate"].apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-int(legs/10))
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-int(legs/10)]
    classified=classified[30:len(classified)-int(legs/10)]
    
    print(c)
    
    print(classified.isnull().sum())
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)
#print(y_train.isnull().any())
#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
print(clf.feature_importances_)

[182900, 193365]
class    0
dtype: int64
0.5464005209510013
[[18239 18656]
 [15476 22876]]
[0.54097583 0.5508042 ]
[0.03089567 0.00225083 0.00227094 0.0023678  0.00237271 0.00242215
 0.00243017 0.00238422 0.00236787 0.00237018 0.0024425  0.00235882
 0.00225201 0.02260825 0.         0.         0.         0.
 0.         0.         0.         0.02480127 0.02403885 0.02730564
 0.02501402 0.02459327 0.02484997 0.02734432 0.02694795 0.02631672
 0.02609477 0.02595314 0.02622143 0.02595873 0.02591201 0.02570516
 0.02584274 0.025679   0.0258628  0.02577572 0.02580065 0.02573175
 0.02551259 0.02552885 0.02544952 0.02522874 0.0254438  0.02485289
 0.02513222 0.02489566 0.02493321 0.02477481 0.02464281 0.02459323
 0.02481125 0.02500072 0.02565568]


In [7]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "Close",
        "January","February","March","April","May","June",
        "July","August","September","October","November","December",
        "day",
        "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ"#,
#         "10m_rate",
#         "20m_rate",
#         "30m_rate",
#         "40m_rate",
#         "50m_rate",
#         "60m_rate",
#         "70m_rate",
#         "80m_rate",
#         "90m_rate",
#         "100m_rate",
#         "110m_rate",
#         "120m_rate",
#         "130m_rate",
#         "140m_rate",
#         "150m_rate",
#         "160m_rate",
#         "170m_rate",
#         "180m_rate",
#         "190m_rate",
#         "200m_rate",
#         "210m_rate",
#         "220m_rate",
#         "230m_rate",
#         "240m_rate",
#         "250m_rate",
#         "260m_rate",
#         "270m_rate",
#         "280m_rate",
#         "290m_rate",
#         "300m_rate"
        ])


    df_feature["Close"] = df["Close"]
    
    df_feature["January"] = df["January"]
    df_feature["February"] = df["February"]
    df_feature["March"] = df["March"]
    df_feature["April"] = df["April"]
    df_feature["May"] = df["May"]
    df_feature["June"] = df["June"]
    df_feature["July"] = df["July"]
    df_feature["August"] = df["August"]
    df_feature["September"] = df["September"]
    df_feature["October"] = df["October"]
    df_feature["November"] = df["November"]
    df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

    df_feature["Sunday"] = df["Sunday"]
    df_feature["Monday"] = df["Monday"]
    df_feature["Thuesday"] = df["Thuesday"]
    df_feature["Wednesday"] = df["Wednesday"]
    df_feature["Thursday"] = df["Thursday"]
    df_feature["Friday"] = df["Friday"]
    df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    
#     i = 10
#     while i != 300 + 10:
#         df_feature[str(i)+"m_rate"] = df["Close"].pct_change(int(i/10))*100
#         i += 10
#     df_feature["10m_rate"] = df["Close"].pct_change()*100
#     df_feature["30m_rate"] = df["Close"].pct_change(3)*100
#     df_feature["60m_rate"] = df["Close"].pct_change(6)*100
#     df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
#     c=[0,0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=0:
#             c[1]+=1
#             return 1
#         elif 0<x<percent:
#             c[2]+=1
#             return 2
#         elif percent<x:
#             c[3]+=1
#             return 3
       
    
#     c=[0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=percent:
#             c[1]+=1
#             return 1
#         elif percent<x:
#             c[2]+=1
#             return 2
       
    
    
    c=[0,0]
    
    
    def classify(x):
        #percent = 0.06

        if x<0:
            c[0]+=1
            return 0
        elif 0<=x:
            c[1]+=1
            return 1

        
        
    legs = 60
    
    classified = pd.DataFrame(columns=["class"])
    classified["class"] = (df["Close"].pct_change(int(legs/10))*100).apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-int(legs/10))
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-int(legs/10)]
    classified=classified[30:len(classified)-int(legs/10)]
    
    print(c)
    
    print(classified.isnull().sum())
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)
#print(y_train.isnull().any())
#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
print(clf.feature_importances_)

[182900, 193365]
class    0
dtype: int64
0.640942496046354
[[22411 14137]
 [12881 25818]]
[0.63501643 0.64617695]
[0.13409947 0.00532727 0.00521763 0.00537635 0.00493832 0.00493109
 0.00481224 0.00531981 0.00501303 0.00522609 0.00544647 0.00423991
 0.00424521 0.08500023 0.         0.         0.         0.
 0.         0.         0.         0.11817354 0.11865165 0.12266496
 0.12003965 0.1207126  0.12056447]


In [19]:
import numpy as np 
import pandas as pd
import matplotlib as plt
from IPython.display import display
import talib as ta


def adjust_data(dataname):
    df = pd.read_csv(dataname, index_col='Datetime')

    
    #以降全ての計算でレート終値を使う
    close = np.array(df["Close"])
    
    
    #特徴量を入れるための空のdataframeを作成
    df_feature = pd.DataFrame(columns=[ 
        "Close",
        "hour_range",
#         "January","February","March","April","May","June",
#         "July","August","September","October","November","December",
        "day",
#         "Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday",
        "SMA_hour/current",
        "SMA_2hour/current",
        "RSI",
        "MACD",
        "BBANDS+2σ",
        "BBANDS-2σ"#,
#         "10m_rate",
#         "20m_rate",
#         "30m_rate",
#         "40m_rate",
#         "50m_rate",
#         "60m_rate",
#         "70m_rate",
#         "80m_rate",
#         "90m_rate",
#         "100m_rate",
#         "110m_rate",
#         "120m_rate",
#         "130m_rate",
#         "140m_rate",
#         "150m_rate",
#         "160m_rate",
#         "170m_rate",
#         "180m_rate",
#         "190m_rate",
#         "200m_rate",
#         "210m_rate",
#         "220m_rate",
#         "230m_rate",
#         "240m_rate",
#         "250m_rate",
#         "260m_rate",
#         "270m_rate",
#         "280m_rate",
#         "290m_rate",
#         "300m_rate"
        ])


    df_feature["Close"] = df["Close"]
    df_feature["hour_range"] = df["hour_range"]
    
#     df_feature["January"] = df["January"]
#     df_feature["February"] = df["February"]
#     df_feature["March"] = df["March"]
#     df_feature["April"] = df["April"]
#     df_feature["May"] = df["May"]
#     df_feature["June"] = df["June"]
#     df_feature["July"] = df["July"]
#     df_feature["August"] = df["August"]
#     df_feature["September"] = df["September"]
#     df_feature["October"] = df["October"]
#     df_feature["November"] = df["November"]
#     df_feature["December"] = df["December"]
    
    #print(df_feature.isnull().any())
    
    #print(df_feature.isnull().any())
    
#     days=["Sunday","Monday","Thuesday","Wednesday","Thursday","Friday","Saturday"]
#     for i in days:
#         df_feature[i] = df[i]

#     df_feature["Sunday"] = df["Sunday"]
#     df_feature["Monday"] = df["Monday"]
#     df_feature["Thuesday"] = df["Thuesday"]
#     df_feature["Wednesday"] = df["Wednesday"]
#     df_feature["Thursday"] = df["Thursday"]
#     df_feature["Friday"] = df["Friday"]
#     df_feature["Saturday"] = df["Saturday"]
    
    
    
    df_feature["day"] = df["day"]
    
#     i = 10
#     while i != 300 + 10:
#         df_feature[str(i)+"m_rate"] = df["Close"].pct_change(int(i/10))*100
#         i += 10
#     df_feature["10m_rate"] = df["Close"].pct_change()*100
#     df_feature["30m_rate"] = df["Close"].pct_change(3)*100
#     df_feature["60m_rate"] = df["Close"].pct_change(6)*100
#     df_feature["120m_rate"] = df["Close"].pct_change(12)*100

    
    
    
    #以下、talibを用いてテクニカル指標（今回の学習で用いる特徴量）を算出しdf_feature入れる

    #単純移動平均は、単純移動平均値とその日の終値の比を特徴量として用いる
    df_feature["SMA_hour/current"]= ta.SMA(close, timeperiod=6) / close
    df_feature["SMA_2hour/current"]= ta.SMA(close, timeperiod=12) / close

    #RSI
    df_feature["RSI"] = ta.RSI(close, timeperiod=12)

    #MACD
    df_feature["MACD"], _ , _= ta.MACD(close, fastperiod=3, slowperiod=18, signalperiod=9)

    #ボリンジャーバンド 
    upper, middle, lower = ta.BBANDS(close, timeperiod=20, nbdevup=3, nbdevdn=3)
    df_feature["BBANDS+2σ"] = upper / close
    df_feature["BBANDS-2σ"] = lower / close

    
    
#     c=[0,0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=0:
#             c[1]+=1
#             return 1
#         elif 0<x<percent:
#             c[2]+=1
#             return 2
#         elif percent<x:
#             c[3]+=1
#             return 3
       
    
#     c=[0,0,0]
    
    
#     def classify(x):
#         percent = 0.06

#         if x<-percent:
#             c[0]+=1
#             return 0
#         elif -percent<x<=percent:
#             c[1]+=1
#             return 1
#         elif percent<x:
#             c[2]+=1
#             return 2
       
    
    
    c=[0,0]
    
    
    def classify(x):
        #percent = 0.06

        if x<0:
            c[0]+=1
            return 0
        elif 0<=x:
            c[1]+=1
            return 1

        
        
    legs = 60
    
    classified = pd.DataFrame(columns=["class"])
    classified["class"] = (df["Close"].pct_change(int(legs/10))*100).apply(lambda x: classify(x))

    #classified = classified.shift(-1)
    classified = classified.shift(-int(legs/10))
    
    
    #df_adjusted=df_feature[30:len(df_feature)-2]
    #classified=classified[30:len(classified)-2]
    df_adjusted=df_feature[30:len(df_feature)-int(legs/10)]
    classified=classified[30:len(classified)-int(legs/10)]
    
    print(c)
    
    print(classified.isnull().sum())
    
    
    return df_adjusted, classified


from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import optuna


df_adjusted, classified = adjust_data("./2010_1to2019_12.csv")

X_train, X_test, y_train, y_test = train_test_split(df_adjusted, classified["class"], train_size=0.8)


#y_ravel=np.ravel(y_train)
#print(X_train.isnull().any())
#print(X_train, y_train)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
print(accuracy_score(y_test, clf.predict(X_test)))

#X_real, y_real = adjust_data("./USD_JPY_202009_M10.csv")
#print(accuracy_score(y_real, clf.predict(X_real)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, clf.predict(X_test)))

from sklearn.metrics import precision_score
print(precision_score(y_test, clf.predict(X_test), average=None))

import pickle
filename = 'RF_01.sav'
pickle.dump(clf, open(filename, 'wb'))

# print(X_train)
print(clf.feature_importances_)

[182900, 193365]
class    0
dtype: int64
0.6437067258495355
[[22585 13925]
 [12885 25852]]
[0.63673527 0.64992332]
[0.14015376 0.06489428 0.08632392 0.11549055 0.11658106 0.12238688
 0.11792953 0.11784886 0.11839116]
